### ISSUE TITLE
Link to Paper

### ISSUE THREAD

**Issue by vinnnyr** [UniBwTAS/continuous_clustering#1]
Hi!

The README mentions "our paper"

> Add features:
Ground point segmentation:
In our paper we do ground point segmentation by using a accumulated terrain grid

Is this paper yet publicly available? If so, I would love to learn more. 

Thanks!

**Comment by AndreasR30** [comment]
Hello,

Thank you for your interest in our work. Sorry, we didn't expect that this repository gets attention so fast. Luckily, the link to our paper about the continuous clustering was published ( today :) ) on ArXiv: https://arxiv.org/abs/2311.13976

The link to the terrain estimation paper of colleague is here: https://ieeexplore.ieee.org/abstract/document/9827214
As already mentioned in the code of this repository we do not use the terrain estimation yet but rather use a simpler ground point segmentation. That's because the ground point segmentation algorithm from my colleague is not open source yet.
